# Auto-generated test suite for hangman
# Source: legacy_workspace/hangman.py
# Generated by Phoenix QA Engineer

import pytest
import math
from legacy_workspace.hangman import process_transaction


def test_process_transaction_success_0():
    """Test process_transaction(150) == 157.5"""
    result = process_transaction(150)
    assert result == pytest.approx(157.5)


def test_process_transaction_success_1():
    """Test process_transaction('250.75') == 263.2875"""
    result = process_transaction('250.75')
    assert result == pytest.approx(263.2875)


def test_process_transaction_success_2():
    """Test process_transaction('1e6') == 1050000.0"""
    result = process_transaction('1e6')
    assert result == pytest.approx(1050000.0)


def test_process_transaction_success_3():
    """Test process_transaction('   3.5   ') == 3.6750000000000003"""
    result = process_transaction('   3.5   ')
    assert result == pytest.approx(3.6750000000000003)


def test_process_transaction_success_4():
    """Test process_transaction('nan') == float('nan')"""
    result = process_transaction('nan')
    assert result == pytest.approx(float('nan'), nan_ok=True)


def test_process_transaction_success_5():
    """Test process_transaction('inf') == float('inf')"""
    result = process_transaction('inf')
    assert result == pytest.approx(float('inf'))


def test_process_transaction_success_6():
    """Test process_transaction(True) == 1.05"""
    result = process_transaction(True)
    assert result == pytest.approx(1.05)


def test_process_transaction_crash_0():
    """Test process_transaction('-5') raises ValueError."""
    with pytest.raises(ValueError):
        process_transaction('-5')


def test_process_transaction_crash_1():
    """Test process_transaction('0') raises ZeroDivisionError."""
    with pytest.raises(ZeroDivisionError):
        process_transaction('0')

