# Auto-generated test suite for legacy_billing
# Source: legacy_workspace/legacy_billing.py
# Generated by Phoenix QA Engineer

import pytest
import math
from legacy_workspace.legacy_billing import process_transaction


def test_process_transaction_success_0():
    """Test process_transaction(100) == 105.0"""
    result = process_transaction(100)
    assert result == pytest.approx(105.0)


def test_process_transaction_success_1():
    """Test process_transaction('200.50') == 210.525"""
    result = process_transaction('200.50')
    assert result == pytest.approx(210.525)


def test_process_transaction_success_2():
    """Test process_transaction('1e3') == 1050.0"""
    result = process_transaction('1e3')
    assert result == pytest.approx(1050.0)


def test_process_transaction_crash_0():
    """Test process_transaction('0') raises ZeroDivisionError."""
    with pytest.raises(ZeroDivisionError):
        process_transaction('0')


def test_process_transaction_crash_1():
    """Test process_transaction(-5) raises ValueError."""
    with pytest.raises(ValueError):
        process_transaction(-5)


def test_process_transaction_crash_2():
    """Test process_transaction(' -3.14 ') raises ValueError."""
    with pytest.raises(ValueError):
        process_transaction(' -3.14 ')


def test_process_transaction_crash_3():
    """Test process_transaction('') raises ValueError."""
    with pytest.raises(ValueError):
        process_transaction('')


def test_process_transaction_crash_4():
    """Test process_transaction(None) raises TypeError."""
    with pytest.raises(TypeError):
        process_transaction(None)

