import os
import json
from typing import Annotated
from pydantic import Field
from agent_framework import tool


CAPTURES_FILE = os.path.abspath("generated_tests/observer_captures.json")
OUTPUT_DIR = os.path.abspath("generated_tests")


def _load_captures_for_module(module_name: str) -> list[dict]:
    """Load capture records for a specific module."""
    if not os.path.exists(CAPTURES_FILE):
        return []
    with open(CAPTURES_FILE, "r") as f:
        all_records = json.load(f)
    return [r for r in all_records if r.get("module") == module_name]


def _format_value(val) -> str:
    """Format a Python value for use in test code."""
    if val is None:
        return "None"
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, str):
        return repr(val)
    if isinstance(val, (int, float)):
        if isinstance(val, float):
            import math
            if math.isnan(val):
                return "float('nan')"
            if math.isinf(val):
                return "float('inf')" if val > 0 else "float('-inf')"
        return repr(val)
    if isinstance(val, list):
        items = ", ".join(_format_value(v) for v in val)
        return f"[{items}]"
    if isinstance(val, dict):
        items = ", ".join(f"{_format_value(k)}: {_format_value(v)}" for k, v in val.items())
        return "{" + items + "}"
    return repr(val)


def _generate_test_code(module_name: str, legacy_path: str, records: list[dict]) -> str:
    """Generate a complete pytest file from capture records."""
    # Group by function
    by_function = {}
    for r in records:
        func = r.get("function", "unknown")
        if func not in by_function:
            by_function[func] = {"successes": [], "crashes": []}
        if r.get("status") == "success":
            by_function[func]["successes"].append(r)
        else:
            by_function[func]["crashes"].append(r)

    # Build import path: legacy_workspace/hangman.py -> legacy_workspace.hangman
    import_module = legacy_path.replace("/", ".").replace(".py", "")
    all_funcs = list(by_function.keys())
    imports = ", ".join(all_funcs)

    lines = []
    lines.append(f"# Auto-generated test suite for {module_name}")
    lines.append(f"# Source: {legacy_path}")
    lines.append(f"# Generated by Phoenix QA Engineer")
    lines.append("")
    lines.append("import pytest")
    lines.append("import math")
    lines.append(f"from {import_module} import {imports}")
    lines.append("")
    lines.append("")

    test_count = 0
    for func_name, data in by_function.items():
        # Success tests
        for i, record in enumerate(data["successes"]):
            args = record.get("inputs", {}).get("args", [])
            output = record.get("output")

            # Skip tests for outputs that are too large (e.g., load_words)
            output_str = str(output)
            if output_str.startswith("[list of ") or "[truncated]" in output_str or len(output_str) > 500:
                # For large outputs, just test the function doesn't crash
                args_str = ", ".join(_format_value(a) for a in args)
                lines.append(f"def test_{func_name}_success_{i}():")
                lines.append(f"    \"\"\"Test {func_name} returns without error.\"\"\"")
                lines.append(f"    result = {func_name}({args_str})")
                lines.append(f"    assert result is not None")
                lines.append("")
                lines.append("")
                test_count += 1
                continue

            # Detect random/non-deterministic: output is an element of an input list
            is_random_pick = False
            pick_from = None
            for arg in args:
                if isinstance(arg, list) and output in arg:
                    is_random_pick = True
                    pick_from = arg
                    break
                if isinstance(arg, str) and isinstance(output, str) and len(output) == 1 and output in arg:
                    is_random_pick = True
                    pick_from = arg
                    break

            args_str = ", ".join(_format_value(a) for a in args)

            if is_random_pick:
                # Non-deterministic: assert membership instead of exact value
                lines.append(f"def test_{func_name}_success_{i}():")
                lines.append(f"    \"\"\"Test {func_name} returns an element from its input.\"\"\"")
                lines.append(f"    result = {func_name}({args_str})")
                lines.append(f"    assert result in {_format_value(pick_from)}")
                lines.append("")
                lines.append("")
                test_count += 1
                continue

            expected = _format_value(output)

            lines.append(f"def test_{func_name}_success_{i}():")
            lines.append(f"    \"\"\"Test {func_name}({args_str}) == {expected}\"\"\"")
            lines.append(f"    result = {func_name}({args_str})")

            # Handle float comparison
            if isinstance(output, float):
                import math
                if math.isnan(output):
                    lines.append(f"    assert result == pytest.approx({expected}, nan_ok=True)")
                else:
                    lines.append(f"    assert result == pytest.approx({expected})")
            elif isinstance(output, bool):
                lines.append(f"    assert result is {expected}")
            else:
                lines.append(f"    assert result == {expected}")

            lines.append("")
            lines.append("")
            test_count += 1

        # Crash tests
        for i, record in enumerate(data["crashes"]):
            args = record.get("inputs", {}).get("args", [])
            error = record.get("error", "")

            # Parse error type from string like "ValueError: message"
            error_type = "Exception"
            error_msg = ""
            if ": " in error:
                error_type = error.split(":")[0].strip()
                error_msg = error.split(":", 1)[1].strip()
            elif error:
                error_type = error.strip()

            args_str = ", ".join(_format_value(a) for a in args)

            lines.append(f"def test_{func_name}_crash_{i}():")
            lines.append(f"    \"\"\"Test {func_name}({args_str}) raises {error_type}.\"\"\"")
            lines.append(f"    with pytest.raises({error_type}):")
            lines.append(f"        {func_name}({args_str})")
            lines.append("")
            lines.append("")
            test_count += 1

    return "\n".join(lines), test_count


@tool(approval_mode="never_require")
def generate_tests(
    module_name: Annotated[str, Field(description="The module name to generate tests for, e.g. 'hangman' or 'legacy_billing'.")],
    legacy_file_path: Annotated[str, Field(description="The path to the legacy file, e.g. 'legacy_workspace/hangman.py'.")]
) -> str:
    """
    Automatically generate a complete PyTest regression suite for a legacy module.
    Reads the captured runtime data from observer_captures.json and generates
    test cases for every observed success and crash. Saves the test file to
    generated_tests/test_<module_name>.py.

    Call this ONCE per module.
    """
    records = _load_captures_for_module(module_name)
    if not records:
        return f"ERROR: No capture records found for module '{module_name}'."

    test_code, test_count = _generate_test_code(module_name, legacy_file_path, records)

    # Save the test file
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    test_file = os.path.join(OUTPUT_DIR, f"test_{module_name}.py")
    with open(test_file, "w", encoding="utf-8") as f:
        f.write(test_code)

    return (
        f"Generated test__{module_name}.py with {test_count} test cases.\n"
        f"Saved to: {test_file}\n"
        f"Tests cover all observed successes and crashes from the runtime captures."
    )


@tool(approval_mode="never_require")
def save_test_suite(
        code: Annotated[str, Field(description="The complete, raw Python pytest code to save.")],
        file_name: Annotated[str, Field(description="The name of the test file (e.g., test_my_module.py).")]
) -> str:
    """
    Saves a manually written PyTest suite to the local 'generated_tests' directory.
    Use generate_tests instead for automatic generation from captures.
    """
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    file_path = os.path.join(OUTPUT_DIR, file_name)

    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)
        return f"SUCCESS: Test suite successfully saved to {file_path}"
    except Exception as e:
        return f"ERROR: Failed to save test suite. {str(e)}"